fps
frametime=1
cpu_stats
cpu_temp
gpu_stats
gpu_temp
ram
vram
font_size=22
position=top-left
text_color=FFFFFF
gpu_color=2E9762
cpu_color=2E97CB
vram_color=AD64C1
ram_color=C26693
engine_color=EB5B5B
frametime_color=00FF00
background_alpha=0.5
toggle_hud=Shift_R+F12
